/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAgendamentoRouteImport } from './routes/_authenticated/agendamento'
import { Route as AuthenticatedCadastrosPacientesRouteImport } from './routes/_authenticated/cadastros.pacientes'
import { Route as AuthenticatedCadastrosOrientadoresRouteImport } from './routes/_authenticated/cadastros.orientadores'
import { Route as AuthenticatedCadastrosAlunosRouteImport } from './routes/_authenticated/cadastros.alunos'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendamentoRoute =
  AuthenticatedAgendamentoRouteImport.update({
    id: '/agendamento',
    path: '/agendamento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosPacientesRoute =
  AuthenticatedCadastrosPacientesRouteImport.update({
    id: '/cadastros/pacientes',
    path: '/cadastros/pacientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosOrientadoresRoute =
  AuthenticatedCadastrosOrientadoresRouteImport.update({
    id: '/cadastros/orientadores',
    path: '/cadastros/orientadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastrosAlunosRoute =
  AuthenticatedCadastrosAlunosRouteImport.update({
    id: '/cadastros/alunos',
    path: '/cadastros/alunos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/agendamento': typeof AuthenticatedAgendamentoRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/config': typeof AuthenticatedConfigRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/cadastros/alunos': typeof AuthenticatedCadastrosAlunosRoute
  '/cadastros/orientadores': typeof AuthenticatedCadastrosOrientadoresRoute
  '/cadastros/pacientes': typeof AuthenticatedCadastrosPacientesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/agendamento': typeof AuthenticatedAgendamentoRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/config': typeof AuthenticatedConfigRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/': typeof AuthenticatedIndexRoute
  '/cadastros/alunos': typeof AuthenticatedCadastrosAlunosRoute
  '/cadastros/orientadores': typeof AuthenticatedCadastrosOrientadoresRoute
  '/cadastros/pacientes': typeof AuthenticatedCadastrosPacientesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_authenticated/agendamento': typeof AuthenticatedAgendamentoRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cadastros/alunos': typeof AuthenticatedCadastrosAlunosRoute
  '/_authenticated/cadastros/orientadores': typeof AuthenticatedCadastrosOrientadoresRoute
  '/_authenticated/cadastros/pacientes': typeof AuthenticatedCadastrosPacientesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/agendamento'
    | '/calendario'
    | '/config'
    | '/materiais'
    | '/mensagens'
    | '/cadastros/alunos'
    | '/cadastros/orientadores'
    | '/cadastros/pacientes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/agendamento'
    | '/calendario'
    | '/config'
    | '/materiais'
    | '/mensagens'
    | '/'
    | '/cadastros/alunos'
    | '/cadastros/orientadores'
    | '/cadastros/pacientes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/setup'
    | '/_authenticated/agendamento'
    | '/_authenticated/calendario'
    | '/_authenticated/config'
    | '/_authenticated/materiais'
    | '/_authenticated/mensagens'
    | '/_authenticated/'
    | '/_authenticated/cadastros/alunos'
    | '/_authenticated/cadastros/orientadores'
    | '/_authenticated/cadastros/pacientes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agendamento': {
      id: '/_authenticated/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AuthenticatedAgendamentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/pacientes': {
      id: '/_authenticated/cadastros/pacientes'
      path: '/cadastros/pacientes'
      fullPath: '/cadastros/pacientes'
      preLoaderRoute: typeof AuthenticatedCadastrosPacientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/orientadores': {
      id: '/_authenticated/cadastros/orientadores'
      path: '/cadastros/orientadores'
      fullPath: '/cadastros/orientadores'
      preLoaderRoute: typeof AuthenticatedCadastrosOrientadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastros/alunos': {
      id: '/_authenticated/cadastros/alunos'
      path: '/cadastros/alunos'
      fullPath: '/cadastros/alunos'
      preLoaderRoute: typeof AuthenticatedCadastrosAlunosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendamentoRoute: typeof AuthenticatedAgendamentoRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCadastrosAlunosRoute: typeof AuthenticatedCadastrosAlunosRoute
  AuthenticatedCadastrosOrientadoresRoute: typeof AuthenticatedCadastrosOrientadoresRoute
  AuthenticatedCadastrosPacientesRoute: typeof AuthenticatedCadastrosPacientesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendamentoRoute: AuthenticatedAgendamentoRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCadastrosAlunosRoute: AuthenticatedCadastrosAlunosRoute,
  AuthenticatedCadastrosOrientadoresRoute:
    AuthenticatedCadastrosOrientadoresRoute,
  AuthenticatedCadastrosPacientesRoute: AuthenticatedCadastrosPacientesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
